### ISSUE TITLE
Wrap functions on context object.

### ISSUE THREAD

**Issue by Qard** [koajs/trace#1]
It'd be neat if there was a pattern to register functions on the context object to expose them, and conditionally include tracing.

```
app.use(function* (next) {
  this.tracing = Math.random() > 0.5
  this.register('render', render)
  yield* next
})

app.use(function* (next) {
  // The call to `this.render(...)` will automatically include calls for
  // `this.trace('render entry')` and `this.trace('render exit')`
  this.body = this.render('template', { foo: 'bar' })
})
```

**Comment by jonathanong** [comment]
it depends on the object though. sometimes you want to trace before, sometimes you want to trace after.

``` js
var render = this.render;
this.render = function () {
  this.trace('render', arguments);
  return render.apply(this, arguments);
}
```

it's not that hard to do manually :) PR welcomed though!

**Comment by Qard** [comment]
Yep, just thinking out loud. It might be a bit harder for async stuff though, with all the different things you can yield to co.

**Comment by jonathanong** [comment]
@Qard interested in maintaining this module?

**Comment by Qard** [comment]
Unfortunately I'm not using it anymore, so I'm probably not the best candidate. 😕
