### ISSUE TITLE
Support koa 2

### ISSUE THREAD

**Issue by doug-wade** [koajs/trace#7]
In https://github.com/koajs/koala/issues/17, I tried to get koa-trace working with koa 2, and I can't seem to swing it.  I get an error where context is not defined when the trace is ended, at the tail end of the request.  I think there may be some work to do to support koa 2, but I haven't done enough digging to know what that is just yet.

**Comment by haoxins** [comment]
PR welcome ! 👍

**Comment by haoxins** [comment]
Should work fine with v2 IMO.

https://github.com/koajs/trace/blob/master/example.js
